Repository vmtk/vmtk, pull requests merged in 2018-04, with the labels that each got.

#262 Updated Readme
  README.md
  doc/img/home_centerlines.png
  doc/img/home_geometry.png
  doc/img/home_levelset.png
  doc/img/home_mappatch.png
  doc/img/home_mesh.png
Labels: Documentation

#264 bugfix to allow scalar connectivity
  vmtkScripts/vmtksurfaceconnectivity.py
Labels: Bug Fix

#255 add vtkXMLStructuredGridWriter to vmtkimagewriter
  vmtkScripts/vmtkimagewriter.py
Labels: Need Documentation, Need Testing, Need Website Documentation, New Feature

#258 Add Interactive Surface Selection
  vmtkScripts/CMakeLists.txt
  vmtkScripts/vmtkscripts.py
  vmtkScripts/vmtksurfaceconnectivityselector.py
Labels: Need Documentation, Need Testing, New Feature
